### ISSUE TITLE
plugin new!!!!

### ISSUE THREAD

**Issue by MahdiDawat** [callumrawlinson/FlyUI#1]
Like the SimpleAuth plugin that was removed and there is currently no password plugin on the site.

**Comment by callumrawlinson** [comment]
ok! i will make one and upload it. it will take me around 10 mins

**Comment by callumrawlinson** [comment]
@dawatr here you go https://poggit.pmmp.io/p/SimpleAuth/2.1.2-7

**Comment by callumrawlinson** [comment]
@dawatr the one i sent works :)

**Comment by MahdiDawat** [comment]
no
